### PR TITLE
line-list-southafrica.csv

### PR DESCRIPTION
**Pull request by oniemtie**

### CODE REVIEW

**Review by vukosim — CHANGES_REQUESTED** [review]
Can you make sure it is in this format of line-list-africa.csv.

**Comment by oniemtie** [comment]
There is already a file with this name: line-list-africa.csv

**Comment by oniemtie** [comment]
Do you want me to change the name, or the file must have all the columns contained in line-list-africa.csv.

**Comment by vukosim** [comment]
the file must have the columns in line-list-africa (in the same way)

**Comment by oniemtie** [comment]
I have made changed the files according to the line-list-africa however most of the stats that is provided by the gov is missing a lot of information

**Comment by vukosim** [comment]
Thank you for this. I have made a direct move from covid19za to here and made edits. 

For now I will close this request. Pull from the repo for the new line-list-south-africa.csv

**Pull request closed without merging**
