### PR TITLE
Update line_list_Namibia.CSV

### PR DESCRIPTION
**Pull request by HerkulaasCombrink**
Updated male age

### CODE REVIEW

**Comment by vukosim** [comment]
Please sync your repo. I changed the name to match the format

**Review by HerkulaasCombrink — COMMENTED** [review]
Changed the age of the Male to 35 - incorrect age was loaded

**Comment by vukosim** [comment]
Ill make the fix.

**Comment by HerkulaasCombrink** [comment]
Thank you. Git Bash issues, going online - filing an issue

**Pull request closed without merging**
