### PR TITLE
Update to Nigeria List and Gambia List

### PR DESCRIPTION
**Pull request by deelearn**

### CODE REVIEW

**Review by vukosim — CHANGES_REQUESTED** [review]
Your date formats dont match. Please rename Nigeria list correctly

**Comment by deelearn** [comment]
> Your date formats dont match. Please rename Nigeria list correctly
My apologies. Date format in Nigeria list changed and Nigeria list renamed.

**Comment by vukosim** [comment]
should be line-list-nigeria.csv

note the small letters throughout.

Good job as well.

**Comment by vukosim** [comment]
Gamibia should also be line-list-gambia.csv

**Comment by deelearn** [comment]
> Gamibia should also be line-list-gambia.csv

Please pardon my "impeccable" attention to detail :-/. Changes made.

**Comment by vukosim** [comment]
Last one. It should be one line-list-nigeria.csv file.

**Comment by deelearn** [comment]
Deleted old file. One file for line-list-nigeria available.

**Review by vukosim — APPROVED** [review]

**Pull request merged**
